# Generated by Django 5.2 on 2026-04-30 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encomienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=8)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('PE', 'Pendiente'), ('TR', 'En tránsito'), ('EN', 'Entregado'), ('DV', 'Devuelto')], default='PE', max_length=2)),
                ('fecha_envio', models.DateField(auto_now_add=True)),
                ('fecha_entrega_est', models.DateField()),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encomiendas_recibidas', to='clientes.cliente')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encomiendas_enviadas', to='clientes.cliente')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutas.ruta')),
            ],
            options={
                'verbose_name': 'Encomienda',
                'verbose_name_plural': 'Encomiendas',
                'db_table': 'encomiendas',
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
