# Generated by Django 5.2 on 2026-04-30 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0002_empleado_alter_encomienda_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterModelOptions(
            name='encomienda',
            options={'ordering': ['-fecha_envio'], 'verbose_name': 'Encomienda', 'verbose_name_plural': 'Encomiendas'},
        ),
        migrations.AlterModelOptions(
            name='historialestado',
            options={'ordering': ['-fecha'], 'verbose_name': 'Historial de Estado', 'verbose_name_plural': 'Historial de Estados'},
        ),
        migrations.AlterModelTable(
            name='empleado',
            table='empleados',
        ),
        migrations.AlterModelTable(
            name='encomienda',
            table='encomiendas',
        ),
        migrations.AlterModelTable(
            name='historialestado',
            table='historial_estados',
        ),
    ]
